/**
 * Database Query Utility Functions
 *
 * This module provides typed utility functions for all main database operations
 * in the Story Pointer application. All functions include:
 * - Full TypeScript type safety
 * - Error handling with descriptive messages
 * - Row Level Security (RLS) enforcement
 * - Proper null/undefined handling
 *
 * Usage:
 * ```ts
 * import { getRoomByCode, createRoom, joinRoom } from '@/lib/supabase/queries';
 *
 * const room = await getRoomByCode('ABC12345');
 * const newRoom = await createRoom('Sprint Planning', 'fibonacci');
 * const participant = await joinRoom(room.id, userId, 'John Doe');
 * ```
 *
 * @see /docs/database-schema.md for schema documentation
 * @see /docs/rls-policies.md for access control details
 */

import { supabase } from './client';
import type { Tables, Enums } from './client';

/**
 * Custom error class for database operations
 */
export class DatabaseError extends Error {
  code?: string;
  details?: unknown;

  constructor(
    message: string,
    code?: string,
    details?: unknown
  ) {
    super(message);
    this.name = 'DatabaseError';
    this.code = code;
    this.details = details;
  }
}

// ============================================================================
// ROOM OPERATIONS
// ============================================================================

/**
 * Get a room by its room code
 *
 * @param roomCode - The 8-character alphanumeric room code (case-insensitive)
 * @returns Room data if found, null if not found
 * @throws DatabaseError if the query fails
 */
export async function getRoomByCode(
  roomCode: string
): Promise<Tables<'rooms'> | null> {
  try {
    const { data, error } = await supabase
      .from('rooms')
      .select('*')
      .eq('room_code', roomCode.toUpperCase())
      .maybeSingle();

    if (error) {
      throw new DatabaseError(
        `Failed to get room by code: ${error.message}`,
        error.code,
        error
      );
    }

    return data;
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while getting room by code',
      undefined,
      err
    );
  }
}

/**
 * Create a new room
 *
 * The room code is automatically generated by the database trigger.
 * The creator becomes the first participant and is assigned as leader.
 *
 * @param name - Display name for the room
 * @param pointScale - Estimation scale ('fibonacci' or 't-shirt')
 * @returns The created room data
 * @throws DatabaseError if creation fails
 */
export async function createRoom(
  name: string,
  pointScale: Enums<'point_scale_enum'> = 'fibonacci'
): Promise<Tables<'rooms'>> {
  try {
    // Generate a room code using the database function
    const { data: roomCode, error: codeError } = await supabase
      .rpc('generate_room_code');

    if (codeError || !roomCode) {
      throw new DatabaseError(
        `Failed to generate room code: ${codeError?.message || 'Unknown error'}`,
        codeError?.code,
        codeError
      );
    }

    const { data, error } = await supabase
      .from('rooms')
      .insert({
        name,
        point_scale: pointScale,
        room_code: roomCode,
      })
      .select()
      .single();

    if (error) {
      throw new DatabaseError(
        `Failed to create room: ${error.message}`,
        error.code,
        error
      );
    }

    if (!data) {
      throw new DatabaseError('Room created but no data returned');
    }

    return data;
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while creating room',
      undefined,
      err
    );
  }
}

/**
 * Update room settings
 *
 * Only the room leader can update the room.
 * RLS policies enforce this restriction at the database level.
 *
 * @param roomId - UUID of the room to update
 * @param updates - Partial room data to update
 * @returns Updated room data
 * @throws DatabaseError if update fails or user is not leader
 */
export async function updateRoom(
  roomId: string,
  updates: { name?: string; point_scale?: Enums<'point_scale_enum'> }
): Promise<Tables<'rooms'>> {
  try {
    const { data, error } = await supabase
      .from('rooms')
      .update(updates)
      .eq('id', roomId)
      .select()
      .single();

    if (error) {
      // RLS policy will prevent update if user is not leader
      if (error.code === 'PGRST116') {
        throw new DatabaseError(
          'Only the room leader can update room settings',
          error.code,
          error
        );
      }
      throw new DatabaseError(
        `Failed to update room: ${error.message}`,
        error.code,
        error
      );
    }

    if (!data) {
      throw new DatabaseError('Room updated but no data returned');
    }

    return data;
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while updating room',
      undefined,
      err
    );
  }
}

// ============================================================================
// PARTICIPANT OPERATIONS
// ============================================================================

/**
 * Join a room as a participant
 *
 * Handles the following scenarios:
 * - If user already has a participant record in this room, reactivates it
 * - If this is a new participant, creates a new record
 * - If this is the first participant, they become the leader
 *
 * @param roomId - UUID of the room to join
 * @param userId - UUID of the current user. Required: `participants_insert`
 *   checks `user_id = auth.uid()`, so a row cannot be created for anyone else.
 * @param name - Display name for this participant in the room
 * @returns The participant record (existing or newly created)
 * @throws DatabaseError if join fails
 */
export async function joinRoom(
  roomId: string,
  userId: string,
  name: string
): Promise<Tables<'participants'>> {
  try {
    // Every visitor holds a session (anonymous or provider), so this always
    // runs: rejoining a room reuses your row instead of creating a duplicate.
    {
      const { data: existing } = await supabase
        .from('participants')
        .select('*')
        .eq('room_id', roomId)
        .eq('user_id', userId)
        .maybeSingle();

      if (existing) {
        // Reactivate existing participant
        const { data, error } = await supabase
          .from('participants')
          .update({
            is_active: true,
            joined_at: new Date().toISOString(),
            name, // Allow updating display name
          })
          .eq('id', existing.id)
          .select()
          .single();

        if (error) {
          throw new DatabaseError(
            `Failed to reactivate participant: ${error.message}`,
            error.code,
            error
          );
        }

        return data!;
      }
    }

    // Check if this will be the first participant (and thus the leader)
    const { count } = await supabase
      .from('participants')
      .select('*', { count: 'exact', head: true })
      .eq('room_id', roomId);

    const isFirstParticipant = count === 0;

    // Create new participant
    const { data, error } = await supabase
      .from('participants')
      .insert({
        room_id: roomId,
        user_id: userId,
        name,
        is_leader: isFirstParticipant,
        is_active: true,
      })
      .select()
      .single();

    if (error) {
      throw new DatabaseError(
        `Failed to join room: ${error.message}`,
        error.code,
        error
      );
    }

    if (!data) {
      throw new DatabaseError('Participant created but no data returned');
    }

    // If this is the first participant, update room.leader_id
    if (isFirstParticipant) {
      await supabase
        .from('rooms')
        .update({ leader_id: data.id })
        .eq('id', roomId);
    }

    return data;
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while joining room',
      undefined,
      err
    );
  }
}

/**
 * Get all active participants in a room
 *
 * @param roomId - UUID of the room
 * @returns Array of active participant records
 * @throws DatabaseError if query fails
 */
export async function getActiveParticipants(
  roomId: string
): Promise<Tables<'participants'>[]> {
  try {
    const { data, error } = await supabase
      .from('participants')
      .select('*')
      .eq('room_id', roomId)
      .eq('is_active', true)
      .order('joined_at', { ascending: true });

    if (error) {
      throw new DatabaseError(
        `Failed to get active participants: ${error.message}`,
        error.code,
        error
      );
    }

    return data || [];
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while getting active participants',
      undefined,
      err
    );
  }
}

/**
 * Leave a room (set is_active to false)
 *
 * If the participant is the leader, the database trigger will automatically
 * promote another active participant to leader.
 *
 * @param participantId - UUID of the participant record
 * @throws DatabaseError if update fails
 */
export async function leaveRoom(participantId: string): Promise<void> {
  try {
    const { error } = await supabase
      .from('participants')
      .update({ is_active: false })
      .eq('id', participantId);

    if (error) {
      throw new DatabaseError(
        `Failed to leave room: ${error.message}`,
        error.code,
        error
      );
    }
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while leaving room',
      undefined,
      err
    );
  }
}

// ============================================================================
// STORY OPERATIONS
// ============================================================================

/**
 * Create a new story in a room
 *
 * Only the room leader can create stories.
 * RLS policies enforce this restriction at the database level.
 *
 * @param roomId - UUID of the room
 * @param title - Story title
 * @param description - Optional story description
 * @returns The created story data
 * @throws DatabaseError if creation fails or user is not leader
 */
export async function createStory(
  roomId: string,
  title: string,
  description?: string
): Promise<Tables<'stories'>> {
  try {
    const { data, error } = await supabase
      .from('stories')
      .insert({
        room_id: roomId,
        title,
        description: description || null,
        is_active: false, // Leader activates it when ready
      })
      .select()
      .single();

    if (error) {
      // RLS policy will prevent insert if user is not leader
      if (error.code === 'PGRST116') {
        throw new DatabaseError(
          'Only the room leader can create stories',
          error.code,
          error
        );
      }
      throw new DatabaseError(
        `Failed to create story: ${error.message}`,
        error.code,
        error
      );
    }

    if (!data) {
      throw new DatabaseError('Story created but no data returned');
    }

    return data;
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while creating story',
      undefined,
      err
    );
  }
}

/**
 * Set a story as active (deactivates all other stories in the room)
 *
 * Only the room leader can activate stories.
 * RLS policies enforce this restriction at the database level.
 *
 * @param storyId - UUID of the story to activate
 * @returns The updated story data
 * @throws DatabaseError if update fails or user is not leader
 */
export async function setActiveStory(
  storyId: string
): Promise<Tables<'stories'>> {
  try {
    // Get the story to find its room_id
    const { data: story, error: storyError } = await supabase
      .from('stories')
      .select('room_id')
      .eq('id', storyId)
      .single();

    if (storyError || !story) {
      throw new DatabaseError(
        `Failed to get story: ${storyError?.message || 'Story not found'}`,
        storyError?.code,
        storyError
      );
    }

    // Deactivate all stories in the room
    await supabase
      .from('stories')
      .update({ is_active: false })
      .eq('room_id', story.room_id);

    // Activate the target story
    const { data, error } = await supabase
      .from('stories')
      .update({ is_active: true })
      .eq('id', storyId)
      .select()
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        throw new DatabaseError(
          'Only the room leader can activate stories',
          error.code,
          error
        );
      }
      throw new DatabaseError(
        `Failed to activate story: ${error.message}`,
        error.code,
        error
      );
    }

    if (!data) {
      throw new DatabaseError('Story activated but no data returned');
    }

    return data;
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while activating story',
      undefined,
      err
    );
  }
}

/**
 * Clear the active story in a room (deactivates all stories)
 *
 * This is used to return to the story creation form after voting is complete.
 * Only the room leader can clear the active story.
 * RLS policies enforce this restriction at the database level.
 *
 * @param roomId - UUID of the room
 * @throws DatabaseError if update fails or user is not leader
 */
export async function clearActiveStory(roomId: string): Promise<void> {
  try {
    const { error } = await supabase
      .from('stories')
      .update({ is_active: false })
      .eq('room_id', roomId);

    if (error) {
      if (error.code === 'PGRST116') {
        throw new DatabaseError(
          'Only the room leader can clear active story',
          error.code,
          error
        );
      }
      throw new DatabaseError(
        `Failed to clear active story: ${error.message}`,
        error.code,
        error
      );
    }
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while clearing active story',
      undefined,
      err
    );
  }
}

/**
 * Get the active story in a room
 *
 * @param roomId - UUID of the room
 * @returns The active story or null if no story is active
 * @throws DatabaseError if query fails
 */
export async function getActiveStory(
  roomId: string
): Promise<Tables<'stories'> | null> {
  try {
    const { data, error } = await supabase
      .from('stories')
      .select('*')
      .eq('room_id', roomId)
      .eq('is_active', true)
      .maybeSingle();

    if (error) {
      throw new DatabaseError(
        `Failed to get active story: ${error.message}`,
        error.code,
        error
      );
    }

    return data;
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while getting active story',
      undefined,
      err
    );
  }
}

// ============================================================================
// VOTE OPERATIONS
// ============================================================================

/**
 * Submit or update a vote for a story
 *
 * If the participant already has a vote for this story, it will be updated.
 * Otherwise, a new vote record is created.
 *
 * @param storyId - UUID of the story being voted on
 * @param participantId - UUID of the participant submitting the vote
 * @param pointValue - The estimate value (string to support different scales)
 * @param sentiment - Optional sentiment indicator (e.g., 'confident', 'concerned')
 * @returns The vote data (existing or newly created)
 * @throws DatabaseError if submission fails
 */
export async function submitVote(
  storyId: string,
  participantId: string,
  pointValue: string,
  sentiment?: string
): Promise<Tables<'votes'>> {
  try {
    // Try to upsert (insert or update if exists)
    const { data, error } = await supabase
      .from('votes')
      .upsert(
        {
          story_id: storyId,
          participant_id: participantId,
          point_value: pointValue,
          sentiment: sentiment || null,
        },
        {
          onConflict: 'story_id,participant_id',
        }
      )
      .select()
      .single();

    if (error) {
      throw new DatabaseError(
        `Failed to submit vote: ${error.message}`,
        error.code,
        error
      );
    }

    if (!data) {
      throw new DatabaseError('Vote submitted but no data returned');
    }

    return data;
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while submitting vote',
      undefined,
      err
    );
  }
}

/**
 * Reveal all votes for a story
 *
 * Goes through the `reveal_votes` database function rather than an UPDATE.
 * RLS grants permission per row, never per column, so a leader-shaped UPDATE
 * policy on votes would also let the leader rewrite other people's estimates.
 * The function checks leadership and touches only `is_revealed`.
 *
 * @param storyId - UUID of the story to reveal votes for
 * @throws DatabaseError if reveal fails or the caller is not the leader
 */
export async function revealVotes(storyId: string): Promise<void> {
  try {
    const { error } = await supabase.rpc('reveal_votes', {
      target_story_id: storyId,
    });

    if (error) {
      // The function raises insufficient_privilege for a non-leader caller.
      if (error.code === '42501') {
        throw new DatabaseError(
          'Only the room leader can reveal votes',
          error.code,
          error
        );
      }
      throw new DatabaseError(
        `Failed to reveal votes: ${error.message}`,
        error.code,
        error
      );
    }
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while revealing votes',
      undefined,
      err
    );
  }
}

/**
 * Get all votes for a story
 *
 * Note: RLS policies enforce that users can only see:
 * - Their own votes (regardless of is_revealed)
 * - Other users' votes where is_revealed=true
 *
 * @param storyId - UUID of the story
 * @returns Array of vote records
 * @throws DatabaseError if query fails
 */
export async function getStoryVotes(
  storyId: string
): Promise<Tables<'votes'>[]> {
  try {
    const { data, error } = await supabase
      .from('votes')
      .select('*')
      .eq('story_id', storyId)
      .order('created_at', { ascending: true });

    if (error) {
      throw new DatabaseError(
        `Failed to get story votes: ${error.message}`,
        error.code,
        error
      );
    }

    return data || [];
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while getting story votes',
      undefined,
      err
    );
  }
}

/**
 * Update the final average for a story after votes are revealed
 *
 * Only the room leader can update story data.
 * RLS policies enforce this restriction at the database level.
 *
 * @param storyId - UUID of the story
 * @param finalAverage - The calculated average estimate
 * @throws DatabaseError if update fails or user is not leader
 */
export async function updateStoryAverage(
  storyId: string,
  finalAverage: number
): Promise<void> {
  try {
    const { error } = await supabase
      .from('stories')
      .update({ final_average: finalAverage })
      .eq('id', storyId);

    if (error) {
      if (error.code === 'PGRST116') {
        throw new DatabaseError(
          'Only the room leader can update story data',
          error.code,
          error
        );
      }
      throw new DatabaseError(
        `Failed to update story average: ${error.message}`,
        error.code,
        error
      );
    }
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while updating story average',
      undefined,
      err
    );
  }
}

// ============================================================================
// PROFILE OPERATIONS
// ============================================================================

/**
 * Get a user's profile by their user ID
 *
 * @param userId - UUID of the authenticated user
 * @returns Profile data if found, null if not found
 * @throws DatabaseError if query fails
 */
export async function getProfile(
  userId: string
): Promise<Tables<'profiles'> | null> {
  try {
    const { data, error } = await supabase
      .from('profiles')
      .select('*')
      .eq('user_id', userId)
      .maybeSingle();

    if (error) {
      throw new DatabaseError(
        `Failed to get profile: ${error.message}`,
        error.code,
        error
      );
    }

    return data;
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while getting profile',
      undefined,
      err
    );
  }
}

/**
 * Create a new profile for an authenticated user
 *
 * @param userId - UUID of the authenticated user
 * @param displayName - User's display name
 * @returns The created profile data
 * @throws DatabaseError if creation fails
 */
export async function createProfile(
  userId: string,
  displayName: string
): Promise<Tables<'profiles'>> {
  try {
    const { data, error } = await supabase
      .from('profiles')
      .insert({
        user_id: userId,
        display_name: displayName,
      })
      .select()
      .single();

    if (error) {
      throw new DatabaseError(
        `Failed to create profile: ${error.message}`,
        error.code,
        error
      );
    }

    if (!data) {
      throw new DatabaseError('Profile created but no data returned');
    }

    return data;
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while creating profile',
      undefined,
      err
    );
  }
}

/**
 * Update a user's profile display name
 *
 * @param userId - UUID of the authenticated user
 * @param displayName - New display name
 * @returns The updated profile data
 * @throws DatabaseError if update fails
 */
export async function updateProfile(
  userId: string,
  displayName: string
): Promise<Tables<'profiles'>> {
  try {
    const { data, error } = await supabase
      .from('profiles')
      .update({ display_name: displayName })
      .eq('user_id', userId)
      .select()
      .single();

    if (error) {
      throw new DatabaseError(
        `Failed to update profile: ${error.message}`,
        error.code,
        error
      );
    }

    if (!data) {
      throw new DatabaseError('Profile updated but no data returned');
    }

    return data;
  } catch (err) {
    if (err instanceof DatabaseError) throw err;
    throw new DatabaseError(
      'Unexpected error while updating profile',
      undefined,
      err
    );
  }
}
